-- Esquema portable H2 / PostgreSQL
CREATE TABLE IF NOT EXISTS tbl_regions (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tbl_customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    photo_url  VARCHAR(500),
    region_id  BIGINT REFERENCES tbl_regions (id),
    state      VARCHAR(50)
);
