{
 "title": "Online Store — Overview",
 "tags": [
  "spring-boot",
  "digitallab"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Servicios up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "up" }
   ]
  },
  {
   "title": "HTTP requests (rate 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}