-- Esquema portable H2 / PostgreSQL (ddl-auto=none; inicialización por script)
CREATE TABLE IF NOT EXISTS tbl_categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(1000),
    stock       DOUBLE PRECISION,
    price       DOUBLE PRECISION,
    status      VARCHAR(50),
    create_at   DATE,
    category_id BIGINT REFERENCES tbl_categories (id)
);
