-- Esquema portable H2 / PostgreSQL
CREATE TABLE IF NOT EXISTS tbl_invoices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number_invoice VARCHAR(255),
    description    VARCHAR(1000),
    customer_id    BIGINT,
    create_at      DATE,
    state          VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS tbl_invoice_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   DOUBLE PRECISION,
    price      DOUBLE PRECISION,
    product_id BIGINT,
    invoice_id BIGINT REFERENCES tbl_invoices (id)
);

-- Ep. 12 — tabla Outbox: eventos escritos en la misma transacción que la factura.
CREATE TABLE IF NOT EXISTS outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(100),
    aggregate_id   BIGINT,
    event_type     VARCHAR(100),
    payload        VARCHAR(4000),
    created_at     TIMESTAMP,
    sent           BOOLEAN DEFAULT FALSE
);
